{"name": "test_network_change", "status": "broken", "statusDetails": {"message": "TypeError: 'list' object is not callable", "trace": "self = <test_login.TestNetwork object at 0x0000020BB9C37BB0>\n\n    def test_network_change(self):\n>       self.networksetting.mobile_network()\nE       TypeError: 'list' object is not callable\n\nscripts\\test_login.py:18: TypeError"}, "start": 1593070483808, "stop": 1593070483808, "uuid": "f0f68be3-01c8-458e-856c-a50641232cfa", "historyId": "cd345822355bc64e37af83afe6895c2a", "testCaseId": "122af2a558ac99b9cf2703bd9141ede8", "fullName": "scripts.test_login.TestNetwork#test_network_change", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestNetwork"}, {"name": "host", "value": "LAPTOP-7ES49RD3"}, {"name": "thread", "value": "1120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}