{"uuid": "1ebf96e7-1f6e-4e9e-a9db-3fad910ecfce", "children": ["2d557274-b247-440a-8a9a-0158fcb7dc0c"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "TypeError: nextone() missing 1 required positional argument: 'self'\n", "trace": "  File \"e:\\python3.8\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 722, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 660, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\数据分析\\scripts\\test_login.py\", line 12, in setup_class\n    self.driver = TestCalculate.nextone()\n"}, "start": 1593073388248, "stop": 1593073388248}], "start": 1593073388248, "stop": 1593073388545}